export const optionsConfig: Record<string, string> = {
    width: '宽度',
    height: '高度',
    top: "坐标Y",
    left: '坐标X',
    propValue: '内容',
    url: '更换图片',
    fontSize: '字体大小',
    fontWeight: '字体粗细',
    lineHeight: '行高',
    backgroundColor: '背景色',
    textAlign: '对齐方式',
    color: '颜色',
    borderRadius: '圆角',
    linkTo: '链接地址',
    borderWidth: '边框宽度',
    borderColor: '边框颜色',
    borderStyle: '边框样式',
}

export enum OptionsTypes {
    width = 'OInput',
    height = 'OInput',
    top = 'OInput',
    left = 'OInput',
    propValue = 'OInput',
    url = 'OInputFile',
    fontSize = 'OInput',
    fontWeight = 'OInput',
    lineHeight = 'OInput',
    backgroundColor = 'OColorSelector',
    textAlign = 'ORadio',
    color = 'OColorSelector',
    borderRadius = 'OInput',
    linkTo = 'OInput',
    borderWidth = 'OInput',
    borderColor = 'OColorSelector',
    borderStyle = 'ORadio',
}

export enum Options {
    width = 'width',
    height = 'height',
    top = 'top',
    left = 'left',
    propValue = 'propValue',
    url = 'url',
    fontSize = 'fontSize',
    fontWeight = 'fontWeight',
    lineHeight = 'lineHeight',
    backgroundColor = 'backgroundColor',
    textAlign = 'textAlign',
    color = 'color',
    borderRadius = 'borderRadius',
    linkTo = 'linkTo',
    borderWidth = 'borderWidth',
    borderColor = 'borderColor',
    borderStyle = 'borderStyle',
}
